import type { Node, Edge } from "@xyflow/react";
import type {
  SyncNodeData,
  ActionNodeData,
  ModelNodeData,
  ModelField,
  WebhookNodeData,
  NangoProject,
} from "../types/flow";

// ── Public API ───────────────────────────────────────────────────────────

export interface GeneratedFile {
  path: string;
  content: string;
}

/**
 * Walk the visual graph and emit a set of TypeScript files that form a valid
 * Nango integration project. The first file is always `nango.config.ts`,
 * which replaces the deprecated `nango.yaml` format.
 */
export function graphToTypeScript(project: NangoProject, nodes: Node[], edges: Edge[]): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  const modelNodes = nodes.filter((n) => n.type === "model");
  const syncNodes = nodes.filter((n) => n.type === "sync");
  const actionNodes = nodes.filter((n) => n.type === "action");

  // Build a lookup: model label → field list
  const modelMap = new Map<string, ModelField[]>();
  for (const node of modelNodes) {
    const d = node.data as unknown as ModelNodeData;
    modelMap.set(d.label, d.fields ?? []);
  }

  // 1. TypeScript integration config (replaces nango.yaml)
  files.push({
    path: "nango.config.ts",
    content: emitTsConfig(project, nodes, edges),
  });

  // 2. Nango SDK type stubs
  files.push({
    path: "nango-sdk.d.ts",
    content: emitSdkStubs(),
  });

  // 3. Model interfaces
  if (modelNodes.length > 0) {
    files.push({
      path: "models.ts",
      content: emitModels(modelNodes),
    });
  }

  // 4. Sync handlers
  for (const node of syncNodes) {
    const d = node.data as unknown as SyncNodeData;
    const name = toFileName(d.label || node.id);
    files.push({
      path: `syncs/${name}.ts`,
      content: emitSyncHandler(d, modelMap),
    });
  }

  // 5. Action handlers
  for (const node of actionNodes) {
    const d = node.data as unknown as ActionNodeData;
    const name = toFileName(d.label || node.id);
    files.push({
      path: `actions/${name}.ts`,
      content: emitActionHandler(d, modelMap),
    });
  }

  return files;
}

// ── TypeScript config (replaces nango.yaml) ──────────────────────────────

/**
 * Generate `nango.config.ts` — the TypeScript replacement for `nango.yaml`.
 * The structure mirrors the old YAML schema but is expressed as a typed
 * TypeScript object, enabling editor auto-complete and type checking.
 */
function emitTsConfig(project: NangoProject, nodes: Node[], edges: Edge[]): string {
  const provider = project.provider || "unknown";
  const syncNodes = nodes.filter((n) => n.type === "sync");
  const actionNodes = nodes.filter((n) => n.type === "action");
  const webhookNodes = nodes.filter((n) => n.type === "webhook");
  const modelNodes = nodes.filter((n) => n.type === "model");

  /** Resolve output model: explicit ref first, then graph edges. */
  function resolveRef(nodeId: string, explicitRef: string | undefined): string {
    if (explicitRef) return explicitRef;
    const connected = [
      ...edges.filter((e) => e.source === nodeId).map((e) => e.target),
      ...edges.filter((e) => e.target === nodeId).map((e) => e.source),
    ];
    const modelNode = nodes.find((n) => connected.includes(n.id) && n.type === "model");
    if (modelNode) return (modelNode.data as unknown as ModelNodeData).label || modelNode.id;
    return "Unknown";
  }

  /** Quote a key only when it isn't a bare JS identifier. */
  function objKey(s: string): string {
    return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(s) ? s : JSON.stringify(s);
  }

  const p: string[] = [];

  p.push(`/**`);
  p.push(` * Nango integration configuration.`);
  p.push(` * This file replaces the deprecated nango.yaml format.`);
  p.push(` * Generated by Nango Builder — edit with care.`);
  p.push(` */`);
  p.push(``);
  p.push(`const config = {`);
  p.push(`  integrations: {`);
  p.push(`    ${objKey(provider)}: {`);

  if (syncNodes.length > 0) {
    p.push(`      syncs: {`);
    for (const node of syncNodes) {
      const d = node.data as unknown as SyncNodeData;
      const name = d.label || node.id;
      const output = resolveRef(node.id, d.modelRef);
      p.push(`        ${objKey(name)}: {`);
      if (d.description) p.push(`          description: ${JSON.stringify(d.description)},`);
      p.push(`          endpoint: ${JSON.stringify(d.endpoint || "/")},`);
      if (d.method && d.method !== "GET") p.push(`          method: ${JSON.stringify(d.method)},`);
      p.push(`          frequency: ${JSON.stringify(d.frequency || "every 1h")},`);
      p.push(`          output: ${JSON.stringify(output)},`);
      p.push(`        },`);
    }
    p.push(`      },`);
  }

  if (actionNodes.length > 0) {
    p.push(`      actions: {`);
    for (const node of actionNodes) {
      const d = node.data as unknown as ActionNodeData;
      const name = d.label || node.id;
      const output = resolveRef(node.id, d.outputModelRef);
      p.push(`        ${objKey(name)}: {`);
      if (d.description) p.push(`          description: ${JSON.stringify(d.description)},`);
      p.push(`          endpoint: ${JSON.stringify(d.endpoint || "/")},`);
      if (d.method && d.method !== "POST") p.push(`          method: ${JSON.stringify(d.method)},`);
      if (d.inputModelRef) p.push(`          input: ${JSON.stringify(d.inputModelRef)},`);
      p.push(`          output: ${JSON.stringify(output)},`);
      p.push(`        },`);
    }
    p.push(`      },`);
  }

  if (webhookNodes.length > 0) {
    p.push(`      webhooks: {`);
    for (const node of webhookNodes) {
      const d = node.data as unknown as WebhookNodeData;
      const name = d.label || node.id;
      const output = resolveRef(node.id, d.modelRef);
      p.push(`        ${objKey(name)}: {`);
      if (d.description) p.push(`          description: ${JSON.stringify(d.description)},`);
      p.push(`          endpoint: ${JSON.stringify(d.endpoint || "/")},`);
      if (d.method) p.push(`          method: ${JSON.stringify(d.method)},`);
      p.push(`          output: ${JSON.stringify(output)},`);
      p.push(`        },`);
    }
    p.push(`      },`);
  }

  p.push(`    },`);
  p.push(`  },`);

  if (modelNodes.length > 0) {
    p.push(`  models: {`);
    for (const node of modelNodes) {
      const d = node.data as unknown as ModelNodeData;
      const name = d.label || node.id;
      const fields = d.fields ?? [];
      p.push(`    ${objKey(name)}: {`);
      for (const field of fields) {
        // Optional fields use a "name?" string key (Nango convention).
        const key = field.optional ? JSON.stringify(`${field.name}?`) : objKey(field.name);
        p.push(`      ${key}: ${JSON.stringify(field.type)},`);
      }
      p.push(`    },`);
    }
    p.push(`  },`);
  }

  p.push(`} as const;`);
  p.push(``);
  p.push(`export default config;`);
  p.push(``);

  return p.join("\n");
}

// ── Nango SDK type stubs ─────────────────────────────────────────────────

function emitSdkStubs(): string {
  return `/**
 * Nango SDK type stubs for generated integration code.
 * These provide type-safe access to the Nango runtime context.
 */

export interface NangoSync {
  /** Make an authenticated GET request through the Nango proxy. */
  get<T = unknown>(config: ProxyConfig): Promise<ProxyResponse<T>>;
  /** Make an authenticated POST request through the Nango proxy. */
  post<T = unknown>(config: ProxyConfig): Promise<ProxyResponse<T>>;
  /** Make an authenticated PUT request through the Nango proxy. */
  put<T = unknown>(config: ProxyConfig): Promise<ProxyResponse<T>>;
  /** Make an authenticated PATCH request through the Nango proxy. */
  patch<T = unknown>(config: ProxyConfig): Promise<ProxyResponse<T>>;
  /** Make an authenticated DELETE request through the Nango proxy. */
  delete<T = unknown>(config: ProxyConfig): Promise<ProxyResponse<T>>;
  /** Paginate through an API endpoint. Returns an async iterator. */
  paginate<T = unknown>(config: ProxyConfig): AsyncIterable<T[]>;
  /** Persist records to the Nango cache. Each record must have an \`id\` field. */
  batchSave<T extends { id: string | number }>(records: T[], model: string): Promise<void>;
  /** Soft-delete records from the Nango cache. */
  batchDelete<T extends { id: string | number }>(records: T[], model: string): Promise<void>;
  /** Log a message to the Nango execution log. */
  log(message: string, options?: { level?: "debug" | "info" | "warn" | "error" }): void;
  /** Get the current connection metadata. */
  getMetadata<T = Record<string, unknown>>(): Promise<T>;
  /** Retrieve a previously saved checkpoint (incremental sync state). */
  getCheckpoint<T = unknown>(): Promise<T | null>;
  /** Save a checkpoint for resumable incremental syncs. */
  saveCheckpoint(data: unknown): Promise<void>;
}

export interface NangoAction {
  /** Make an authenticated GET request through the Nango proxy. */
  get<T = unknown>(config: ProxyConfig): Promise<ProxyResponse<T>>;
  /** Make an authenticated POST request through the Nango proxy. */
  post<T = unknown>(config: ProxyConfig): Promise<ProxyResponse<T>>;
  /** Make an authenticated PUT request through the Nango proxy. */
  put<T = unknown>(config: ProxyConfig): Promise<ProxyResponse<T>>;
  /** Make an authenticated PATCH request through the Nango proxy. */
  patch<T = unknown>(config: ProxyConfig): Promise<ProxyResponse<T>>;
  /** Make an authenticated DELETE request through the Nango proxy. */
  delete<T = unknown>(config: ProxyConfig): Promise<ProxyResponse<T>>;
  /** Log a message to the Nango execution log. */
  log(message: string, options?: { level?: "debug" | "info" | "warn" | "error" }): void;
  /** Get the current connection metadata. */
  getMetadata<T = Record<string, unknown>>(): Promise<T>;
}

export interface ProxyConfig {
  endpoint: string;
  headers?: Record<string, string>;
  params?: Record<string, string>;
  data?: unknown;
  retries?: number;
  retryOn?: number[];
}

export interface ProxyResponse<T = unknown> {
  data: T;
  status: number;
  headers: Record<string, string>;
}

export class ActionError extends Error {
  payload: Record<string, unknown>;
  constructor(payload: Record<string, unknown>) {
    super(JSON.stringify(payload));
    this.payload = payload;
  }
}
`;
}

// ── Model interfaces ─────────────────────────────────────────────────────

function emitModels(modelNodes: Node[]): string {
  const sections: string[] = [];

  for (const node of modelNodes) {
    const d = node.data as unknown as ModelNodeData;
    const name = toTypeName(d.label);
    const fields = d.fields ?? [];
    sections.push(emitInterface(name, fields));
  }

  return `/**\n * Auto-generated model interfaces from Nango Builder.\n */\n\n${sections.join("\n\n")}\n`;
}

function emitInterface(name: string, fields: ModelField[]): string {
  if (fields.length === 0) {
    return `export interface ${name} {\n  id: string;\n}`;
  }

  const lines = fields.map((f) => {
    const tsType = mapFieldType(f.type);
    const opt = f.optional ? "?" : "";
    return `  ${f.name}${opt}: ${tsType};`;
  });

  // Ensure id field exists (Nango requires it for batchSave)
  const hasId = fields.some((f) => f.name === "id");
  if (!hasId) {
    lines.unshift("  id: string;");
  }

  return `export interface ${name} {\n${lines.join("\n")}\n}`;
}

function mapFieldType(flowType: string): string {
  switch (flowType) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "Date":
      return "string";
    case "string[]":
      return "string[]";
    case "number[]":
      return "number[]";
    case "object":
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

// ── Sync handler ─────────────────────────────────────────────────────────

function emitSyncHandler(
  data: SyncNodeData,
  modelMap: Map<string, ModelField[]>,
): string {
  const modelName = data.modelRef ? toTypeName(data.modelRef) : "Record";
  const hasModel = data.modelRef && modelMap.has(data.modelRef);
  const modelImport = hasModel
    ? `import type { ${modelName} } from "../models";\n`
    : "";
  const outputType = hasModel ? modelName : "Record<string, unknown>";
  const endpoint = data.endpoint || "/";

  return `${modelImport}import type { NangoSync } from "../nango-sdk";

/**
 * ${data.description || `Sync: ${data.label}`}
 *
 * Frequency: ${data.frequency || "every 1h"}
 * Endpoint:  ${(data.method || "GET").toUpperCase()} ${endpoint}
 */
export default async function fetchData(nango: NangoSync): Promise<void> {
  // Paginate through the API and save records to the Nango cache.
  for await (const batch of nango.paginate<${outputType}>({
    endpoint: "${endpoint}",
  })) {
    await nango.batchSave(batch, "${data.modelRef || "Unknown"}");
  }

  nango.log("Sync completed successfully.");
}
`;
}

// ── Action handler ───────────────────────────────────────────────────────

function emitActionHandler(
  data: ActionNodeData,
  modelMap: Map<string, ModelField[]>,
): string {
  const imports: string[] = [];
  const inputType = data.inputModelRef ? toTypeName(data.inputModelRef) : null;
  const outputType = data.outputModelRef
    ? toTypeName(data.outputModelRef)
    : null;

  const modelImports: string[] = [];
  if (inputType && data.inputModelRef && modelMap.has(data.inputModelRef)) {
    modelImports.push(inputType);
  }
  if (
    outputType &&
    data.outputModelRef &&
    modelMap.has(data.outputModelRef) &&
    outputType !== inputType
  ) {
    modelImports.push(outputType);
  }
  if (modelImports.length > 0) {
    imports.push(
      `import type { ${modelImports.join(", ")} } from "../models";`,
    );
  }
  imports.push('import type { NangoAction } from "../nango-sdk";');

  const inputParam = inputType ? `input: ${inputType}` : "";
  const returnType = outputType ? `Promise<${outputType}>` : "Promise<void>";
  const endpoint = data.endpoint || "/";
  const method = (data.method || "POST").toLowerCase();

  return `${imports.join("\n")}

/**
 * ${data.description || `Action: ${data.label}`}
 *
 * Endpoint: ${(data.method || "POST").toUpperCase()} ${endpoint}
 */
export default async function runAction(nango: NangoAction${inputParam ? `, ${inputParam}` : ""}): ${returnType} {
  const response = await nango.${method}<${outputType || "unknown"}>({
    endpoint: "${endpoint}",${inputParam ? "\n    data: input," : ""}
  });

  return response.data;
}
`;
}

// ── Single-node code generation ─────────────────────────────────────

/**
 * Generate the TypeScript handler source for a single sync or action node.
 * Returns `null` for unsupported node types.
 */
export function generateFunctionCode(
  nodeType: string,
  nodeData: SyncNodeData | ActionNodeData,
  modelNodes: Node[],
): string | null {
  const modelMap = new Map<string, ModelField[]>();
  for (const node of modelNodes) {
    const d = node.data as unknown as ModelNodeData;
    modelMap.set(d.label, d.fields ?? []);
  }

  if (nodeType === "sync") {
    return emitSyncHandler(nodeData as SyncNodeData, modelMap);
  }
  if (nodeType === "action") {
    return emitActionHandler(nodeData as ActionNodeData, modelMap);
  }
  return null;
}

// ── Helpers ──────────────────────────────────────────────────────────────

/** Convert a user-facing label to a valid TypeScript identifier (PascalCase). */
function toTypeName(label: string): string {
  return label
    .replace(/[^a-zA-Z0-9\s_-]/g, "")
    .split(/[\s_-]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

/** Convert a user-facing label to a kebab-case filename. */
export function toFileName(label: string): string {
  return label
    .replace(/[^a-zA-Z0-9\s_-]/g, "")
    .trim()
    .toLowerCase()
    .replace(/[\s_]+/g, "-");
}
